# fly.toml app configuration file generated for backend-inshove-v1 on 2025-09-10T11:47:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-inshove-v1'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'performance'
  cpus = 2
  memory_mb = 4096
