app = "inshove-video-processor"
primary_region = "cdg"

[build]

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/health"

[vm]
  cpu_kind = "performance"
  cpus = 2
  memory_mb = 4096

[[mounts]]
  source = "video_data"
  destination = "/app/uploads"

[[mounts]]
  source = "processed_data"  
  destination = "/app/processed"